import slugify from '../utils/slugify'

export default {
  title: "Journal",
  name: 'journal',
  type: "document",
  fields: [
    // {
    //   name: 'devNote',
    //   type: 'note',
    //   options: {
    //     headline: 'Dev Note: Work In Progress',
    //     message: 'This page is a work in progress and may change, please feel free to still use.',
    //     tone: 'caution'
    //   }
    // },
    {
      title: "Title",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Short Title",
      name: "shortTitle",
      type: "string",
      description: "Optional short title which is used when referencing this journal entry within other journal entries (for shorter links).",
    },
    {
      title: "Routed Article",
      name: "routedArticle",
      description: "Toggling this on will create an internal route for this journal entry (used for heavier content pieces)",
      type: "boolean",
      initialValue: false,
    },
    {
      title: "Post Date",
      description: "Press the button to the right to pick a date.",
      name: "date",
      type: "date",
      options: {
        dateFormat: "MMMM Do YYYY",
      },
      validation: Rule => Rule.required()
    },
    {
      title: "Teaser Image",
      name: "heroImage",
      description: "The image used on the grid to tease this journal entry.",
      type: "defaultImage",
      validation: Rule => Rule.required()
    },
    {
      title: 'Related Project Links',
      name: 'projectLinks',
      type: 'array',
      description: 'Optionally add related project links to the journal entry.',
      of: [
        {
          title: 'Project',
          name: 'project',
          type: 'reference',
          to: [{type: 'works'}]
        },
      ],
    },
    {
      title: 'Related Journal Links',
      name: 'journalLinks',
      type: 'array',
      description: 'Optionally add related journal links to the journal entry.',
      of: [
        {
          title: 'Journal',
          name: 'journal',
          type: 'reference',
          to: [{type: 'journal'}]
        },
      ],
    },
    {
      title: 'Related External Links',
      name: 'externalLinks',
      type: 'array',
      description: 'Optionally add related external links to the journal entry.',
      of: [
        {
          title: 'Link',
          name: 'link',
          type: 'object',
          fields: [
            {
              title: 'Link Title',
              name: 'linkTitle',
              type: 'string'
            },
            {
              title: 'Link Url',
              name: 'linkUrl',
              type: 'string'
            }
          ]
        }
      ],
    },
    {
      title: 'Content - Text',
      name: 'contentText',
      type: 'array', 
      of: [{type: 'block'}]
    },
    {
      title: 'Content - Images',
      name: 'contentImages',
      type: 'array',
      of: [
        {
          name: 'image',
          type: 'defaultImage',
          title: 'Image',
        },
      ],
      options: {
        layout: 'grid',
      }
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = ''
          let campaignSlug = ''
          if (doc.title) {
            titleSlug = `${doc.title}`
          } else {
            titleSlug = ''
          }

          if (doc.campaignTitle) {
            campaignSlug = `-${doc.campaignTitle}`
          } else {
            campaignSlug = ''
          }

          return `${titleSlug}${campaignSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    },
  ],
  preview: {
    select: {
      title: 'title',
      images: 'heroImage',
      date: 'date'
    },
    prepare(selection) {
      const {title, date, images} = selection
      return {
        title: title,
        subtitle: date,
        media: images
      }
    }
  }
}